local LSM = LibStub("LibSharedMedia-3.0") 

-- Sounds --
LSM:Register("sound","|cff00ff00Successful|r", [[Interface\Addons\NorskenMedia\Sounds\Successful.ogg]])
-- TTS --
LSM:Register("sound","|cfff900ffAbsorb|r", [[Interface\Addons\NorskenMedia\Sounds\Absorb.ogg]])
LSM:Register("sound","|cfff900ffAbsorbs|r", [[Interface\Addons\NorskenMedia\Sounds\Absorbs.ogg]])
LSM:Register("sound","|cfff900ffAdd Frontal|r", [[Interface\Addons\NorskenMedia\Sounds\Add Frontal.ogg]])
LSM:Register("sound","|cfff900ffAdds Buffed|r", [[Interface\Addons\NorskenMedia\Sounds\Adds Buffed.ogg]])
LSM:Register("sound","|cfff900ffAdds|r", [[Interface\Addons\NorskenMedia\Sounds\Adds.ogg]])
LSM:Register("sound","|cfff900ffAffix Complete|r", [[Interface\Addons\NorskenMedia\Sounds\Affix Complete.ogg]])
LSM:Register("sound","|cfff900ffAffix|r", [[Interface\Addons\NorskenMedia\Sounds\Affix.ogg]])
LSM:Register("sound","|cfff900ffAim Charge|r", [[Interface\Addons\NorskenMedia\Sounds\Aim Charge.ogg]])
LSM:Register("sound","|cfff900ffAoe And Dance|r", [[Interface\Addons\NorskenMedia\Sounds\Aoe And Dance.ogg]])
LSM:Register("sound","|cfff900ffAoe|r", [[Interface\Addons\NorskenMedia\Sounds\Aoe.ogg]])
LSM:Register("sound","|cfff900ffAvoid Tank|r", [[Interface\Addons\NorskenMedia\Sounds\Avoid Tank.ogg]])
LSM:Register("sound","|cfff900ffAvoid|r", [[Interface\Addons\NorskenMedia\Sounds\Avoid.ogg]])
LSM:Register("sound","|cfff900ffBait|r", [[Interface\Addons\NorskenMedia\Sounds\Bait.ogg]])
LSM:Register("sound","|cfff900ffBalls Charging|r", [[Interface\Addons\NorskenMedia\Sounds\Balls Charging.ogg]])
LSM:Register("sound","|cfff900ffBeam|r", [[Interface\Addons\NorskenMedia\Sounds\Beam.ogg]])
LSM:Register("sound","|cfff900ffBeams|r", [[Interface\Addons\NorskenMedia\Sounds\Beams.ogg]])
LSM:Register("sound","|cfff900ffBlade|r", [[Interface\Addons\NorskenMedia\Sounds\Blade.ogg]])
LSM:Register("sound","|cfff900ffBlades|r", [[Interface\Addons\NorskenMedia\Sounds\Blades.ogg]])
LSM:Register("sound","|cfff900ffBlast|r", [[Interface\Addons\NorskenMedia\Sounds\Blast.ogg]])
LSM:Register("sound","|cfff900ffBombs Incoming|r", [[Interface\Addons\NorskenMedia\Sounds\Bombs Incoming.ogg]])
LSM:Register("sound","|cfff900ffBombs|r", [[Interface\Addons\NorskenMedia\Sounds\Bombs.ogg]])
LSM:Register("sound","|cfff900ffBoss Buffed|r", [[Interface\Addons\NorskenMedia\Sounds\Boss Buffed.ogg]])
LSM:Register("sound","|cfff900ffBoss Position|r", [[Interface\Addons\NorskenMedia\Sounds\Boss Position.ogg]])
LSM:Register("sound","|cfff900ffBoss Shielded|r", [[Interface\Addons\NorskenMedia\Sounds\Boss Shielded.ogg]])
LSM:Register("sound","|cfff900ffBox Incoming|r", [[Interface\Addons\NorskenMedia\Sounds\Box Incoming.ogg]])
LSM:Register("sound","|cfff900ffBuffing Add|r", [[Interface\Addons\NorskenMedia\Sounds\Buffing Add.ogg]])
LSM:Register("sound","|cfff900ffCharge|r", [[Interface\Addons\NorskenMedia\Sounds\Charge.ogg]])
LSM:Register("sound","|cfff900ffCharges Incoming|r", [[Interface\Addons\NorskenMedia\Sounds\Charges Incoming.ogg]])
LSM:Register("sound","|cfff900ffCoin Magnet|r", [[Interface\Addons\NorskenMedia\Sounds\Coin Magnet.ogg]])
LSM:Register("sound","|cfff900ffCoin Pull|r", [[Interface\Addons\NorskenMedia\Sounds\Coin Pull.ogg]])
LSM:Register("sound","|cfff900ffCurse|r", [[Interface\Addons\NorskenMedia\Sounds\Curse.ogg]])
LSM:Register("sound","|cfff900ffDance|r", [[Interface\Addons\NorskenMedia\Sounds\Dance.ogg]])
LSM:Register("sound","|cfff900ffDebuff|r", [[Interface\Addons\NorskenMedia\Sounds\Debuff.ogg]])
LSM:Register("sound","|cfff900ffDebuffs|r", [[Interface\Addons\NorskenMedia\Sounds\Debuffs.ogg]])
LSM:Register("sound","|cfff900ffDecurse|r", [[Interface\Addons\NorskenMedia\Sounds\Decurse.ogg]])
LSM:Register("sound","|cfff900ffDispel Tank|r", [[Interface\Addons\NorskenMedia\Sounds\Dispel Tank.ogg]])
LSM:Register("sound","|cfff900ffDmg Amp|r", [[Interface\Addons\NorskenMedia\Sounds\Dmg Amp.ogg]])
LSM:Register("sound","|cfff900ffDodge Together|r", [[Interface\Addons\NorskenMedia\Sounds\Dodge Together.ogg]])
LSM:Register("sound","|cfff900ffDodge|r", [[Interface\Addons\NorskenMedia\Sounds\Dodge.ogg]])
LSM:Register("sound","|cfff900ffFear|r", [[Interface\Addons\NorskenMedia\Sounds\Fear.ogg]])
LSM:Register("sound","|cfff900ffFind Safespot|r", [[Interface\Addons\NorskenMedia\Sounds\Find Safespot.ogg]])
LSM:Register("sound","|cfff900ffFind Soul|r", [[Interface\Addons\NorskenMedia\Sounds\Find Soul.ogg]])
LSM:Register("sound","|cfff900ffFixate Incoming|r", [[Interface\Addons\NorskenMedia\Sounds\Fixate Incoming.ogg]])
LSM:Register("sound","|cfff900ffFixate|r", [[Interface\Addons\NorskenMedia\Sounds\Fixate.ogg]])
LSM:Register("sound","|cfff900ffFlipper|r", [[Interface\Addons\NorskenMedia\Sounds\Flipper.ogg]])
LSM:Register("sound","|cfff900ffFrontal|r", [[Interface\Addons\NorskenMedia\Sounds\Frontal.ogg]])
LSM:Register("sound","|cfff900ffGet Dispelled|r", [[Interface\Addons\NorskenMedia\Sounds\Get Dispelled.ogg]])
LSM:Register("sound","|cfff900ffHeadlock Stun|r", [[Interface\Addons\NorskenMedia\Sounds\Headlock Stun.ogg]])
LSM:Register("sound","|cfff900ffHigh Energy|r", [[Interface\Addons\NorskenMedia\Sounds\High Energy.ogg]])
LSM:Register("sound","|cfff900ffHooks Incoming|r", [[Interface\Addons\NorskenMedia\Sounds\Hooks Incoming.ogg]])
LSM:Register("sound","|cfff900ffIntermission Over|r", [[Interface\Addons\NorskenMedia\Sounds\Intermission Over.ogg]])
LSM:Register("sound","|cfff900ffIntermission|r", [[Interface\Addons\NorskenMedia\Sounds\Intermission.ogg]])
LSM:Register("sound","|cfff900ffKick|r", [[Interface\Addons\NorskenMedia\Sounds\Kick.ogg]])
LSM:Register("sound","|cfff900ffKnock|r", [[Interface\Addons\NorskenMedia\Sounds\Knock.ogg]])
LSM:Register("sound","|cfff900ffKnockback|r", [[Interface\Addons\NorskenMedia\Sounds\Knockback.ogg]])
LSM:Register("sound","|cfff900ffLeap|r", [[Interface\Addons\NorskenMedia\Sounds\Leap.ogg]])
LSM:Register("sound","|cfff900ffLinked|r", [[Interface\Addons\NorskenMedia\Sounds\Linked.ogg]])
LSM:Register("sound","|cfff900ffLinks Incoming|r", [[Interface\Addons\NorskenMedia\Sounds\Links Incoming.ogg]])
LSM:Register("sound","|cfff900ffLook Away|r", [[Interface\Addons\NorskenMedia\Sounds\Look Away.ogg]])
LSM:Register("sound","|cfff900ffMaul|r", [[Interface\Addons\NorskenMedia\Sounds\Maul.ogg]])
LSM:Register("sound","|cfff900ffMax Dmg Amp|r", [[Interface\Addons\NorskenMedia\Sounds\Max Dmg Amp.ogg]])
LSM:Register("sound","|cfff900ffMines|r", [[Interface\Addons\NorskenMedia\Sounds\Mines.ogg]])
LSM:Register("sound","|cfff900ffMiniboss Buffed|r", [[Interface\Addons\NorskenMedia\Sounds\Miniboss Buffed.ogg]])
LSM:Register("sound","|cfff900ffMissile|r", [[Interface\Addons\NorskenMedia\Sounds\Missile.ogg]])
LSM:Register("sound","|cfff900ffMove|r", [[Interface\Addons\NorskenMedia\Sounds\Move.ogg]])
LSM:Register("sound","|cfff900ffNew Add|r", [[Interface\Addons\NorskenMedia\Sounds\New Add.ogg]])
LSM:Register("sound","|cfff900ffOrb|r", [[Interface\Addons\NorskenMedia\Sounds\Orb.ogg]])
LSM:Register("sound","|cfff900ffOrbs|r", [[Interface\Addons\NorskenMedia\Sounds\Orbs.ogg]])
LSM:Register("sound","|cfff900ffPhasing|r", [[Interface\Addons\NorskenMedia\Sounds\Phasing.ogg]])
LSM:Register("sound","|cfff900ffPickaxe|r", [[Interface\Addons\NorskenMedia\Sounds\Pickaxe.ogg]])
LSM:Register("sound","|cfff900ffPools|r", [[Interface\Addons\NorskenMedia\Sounds\Pools.ogg]])
LSM:Register("sound","|cfff900ffPre-Move Inc|r", [[Interface\Addons\NorskenMedia\Sounds\Pre-Move Inc.ogg]])
LSM:Register("sound","|cfff900ffPre-Move|r", [[Interface\Addons\NorskenMedia\Sounds\Pre-Move.ogg]])
LSM:Register("sound","|cfff900ffPre-Spread|r", [[Interface\Addons\NorskenMedia\Sounds\Pre-Spread.ogg]])
LSM:Register("sound","|cfff900ffPull|r", [[Interface\Addons\NorskenMedia\Sounds\Pull.ogg]])
LSM:Register("sound","|cfff900ffPvP Incoming|r", [[Interface\Addons\NorskenMedia\Sounds\PvP Incoming.ogg]])
LSM:Register("sound","|cfff900ffRemove Plating|r", [[Interface\Addons\NorskenMedia\Sounds\Remove Plating.ogg]])
LSM:Register("sound","|cfff900ffRicochet|r", [[Interface\Addons\NorskenMedia\Sounds\Ricochet.ogg]])
LSM:Register("sound","|cfff900ffRun out|r", [[Interface\Addons\NorskenMedia\Sounds\Run out.ogg]])
LSM:Register("sound","|cfff900ffSawblade Incoming|r", [[Interface\Addons\NorskenMedia\Sounds\Sawblade Incoming.ogg]])
LSM:Register("sound","|cfff900ffShield|r", [[Interface\Addons\NorskenMedia\Sounds\Shield.ogg]])
LSM:Register("sound","|cfff900ffSmash|r", [[Interface\Addons\NorskenMedia\Sounds\Smash.ogg]])
LSM:Register("sound","|cfff900ffSmashing|r", [[Interface\Addons\NorskenMedia\Sounds\Smashing.ogg]])
LSM:Register("sound","|cfff900ffSoak|r", [[Interface\Addons\NorskenMedia\Sounds\Soak.ogg]])
LSM:Register("sound","|cfff900ffSoaks|r", [[Interface\Addons\NorskenMedia\Sounds\Soaks.ogg]])
LSM:Register("sound","|cfff900ffSparks|r", [[Interface\Addons\NorskenMedia\Sounds\Sparks.ogg]])
LSM:Register("sound","|cfff900ffSpread|r", [[Interface\Addons\NorskenMedia\Sounds\Spread.ogg]])
LSM:Register("sound","|cfff900ffStack|r", [[Interface\Addons\NorskenMedia\Sounds\Stack.ogg]])
LSM:Register("sound","|cfff900ffStatues|r", [[Interface\Addons\NorskenMedia\Sounds\Statues.ogg]])
LSM:Register("sound","|cfff900ffStop Casting|r", [[Interface\Addons\NorskenMedia\Sounds\Stop Casting.ogg]])
LSM:Register("sound","|cfff900ffStun|r", [[Interface\Addons\NorskenMedia\Sounds\Stun.ogg]])
LSM:Register("sound","|cfff900ffStunned|r", [[Interface\Addons\NorskenMedia\Sounds\Stunned.ogg]])
LSM:Register("sound","|cfff900ffSwap|r", [[Interface\Addons\NorskenMedia\Sounds\Swap.ogg]])
LSM:Register("sound","|cfff900ffSwitch|r", [[Interface\Addons\NorskenMedia\Sounds\Switch.ogg]])
LSM:Register("sound","|cfff900ffTank-Frontal|r", [[Interface\Addons\NorskenMedia\Sounds\Tank-Frontal.ogg]])
LSM:Register("sound","|cfff900ffTornadoes|r", [[Interface\Addons\NorskenMedia\Sounds\Tornadoes.ogg]])
LSM:Register("sound","|cfff900ffTotem|r", [[Interface\Addons\NorskenMedia\Sounds\Totem.ogg]])
LSM:Register("sound","|cfff900ffTransition|r", [[Interface\Addons\NorskenMedia\Sounds\Transition.ogg]])
LSM:Register("sound","|cfff900ffUppercut|r", [[Interface\Addons\NorskenMedia\Sounds\Uppercut.ogg]])
LSM:Register("sound","|cfff900ffWall|r", [[Interface\Addons\NorskenMedia\Sounds\Wall.ogg]])
LSM:Register("sound","|cfff900ffWave|r", [[Interface\Addons\NorskenMedia\Sounds\Wave.ogg]])